"""Precomputed 800m station data (roads/routes/stations/isochrone) generated by
output/isochrone_{mrt,krl,lrt,tj}.py, loaded once at process start so most road-network
queries skip Overpass entirely.

Only covers what those scripts actually produced (backend/data/static/*.geojson) - a mode
with no file yet (e.g. TJ, until its 8091-halte job is run) or a radius beyond what was
precomputed just isn't served here; callers fall back to live osm.roads() in that case.
"""

import json
from pathlib import Path

from shapely.geometry import LineString, Point
from shapely.strtree import STRtree

from .geo import to_m

STATIC_DIR = Path(__file__).resolve().parent.parent / "data" / "static"

# Matches CUTOFF_M in output/isochrone_*.py - the network was only fetched/kept out to
# this distance from each station, so a request for a bigger radius isn't safely coverable.
STATIC_RADIUS_M = 800

_MODES = ("mrt", "krl", "lrt", "tj")

_roads: dict[str, list[dict]] = {}
_trees: dict[str, STRtree] = {}
_lines_m: dict[str, list] = {}
_loaded = False


def _load():
    global _loaded
    if _loaded:
        return
    for mode in _MODES:
        path = STATIC_DIR / f"isochrone_{mode}_roads_800m.geojson"
        roads: list[dict] = []
        lines_m: list = []
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            for f in data["features"]:
                coords = f["geometry"]["coordinates"]
                props = f["properties"]
                roads.append({
                    "coords": coords,
                    "highway": props.get("highway", ""),
                    "sidewalk": props.get("sidewalk", ""),
                    "lit": props.get("lit", ""),
                    "surface": props.get("surface", ""),
                    "wheelchair": props.get("wheelchair", ""),
                })
                lines_m.append(LineString([to_m(Point(lon, lat)) for lon, lat in coords]))
        _roads[mode] = roads
        _lines_m[mode] = lines_m
        _trees[mode] = STRtree(lines_m) if lines_m else STRtree([])
    _loaded = True


def has_mode(mode_label: str) -> bool:
    _load()
    return bool(_roads.get((mode_label or "").lower()))


def roads_near(mode_label: str, lon: float, lat: float, radius: int) -> list[dict] | None:
    """Roads from the precomputed static network within `radius` of (lon, lat), or None
    if this mode has no static data yet or `radius` exceeds STATIC_RADIUS_M - the caller
    should fall back to a live osm.roads() call in either case."""
    _load()
    mode = (mode_label or "").lower()
    roads = _roads.get(mode)
    if not roads or radius > STATIC_RADIUS_M:
        return None
    origin_m = to_m(Point(lon, lat))
    circle = origin_m.buffer(radius)
    tree = _trees[mode]
    lines = _lines_m[mode]
    idxs = tree.query(circle)
    return [roads[i] for i in idxs if lines[i].intersects(circle)]
