"""Precomputed station data (roads/routes/stations/isochrone) generated by
output/isochrone_{mrt,krl,lrt,tj}.py, loaded once at process start so most road-network
queries skip Overpass entirely. Cutoff is 800m for MRT/KRL/LRT, 400m for TJ (see
MODE_RADIUS_M - TJ halte are much denser, so a smaller radius is both enough and lighter).

Only covers what those scripts actually produced (backend/data/static/*.geojson) - a mode
with no file yet or a radius beyond what was precomputed for it just isn't served here;
callers fall back to live osm.roads() in that case.
"""

import json
from pathlib import Path

from shapely.geometry import LineString, Point, shape
from shapely.strtree import STRtree

from .geo import to_m

STATIC_DIR = Path(__file__).resolve().parent.parent / "data" / "static"

_MODES = ("mrt", "krl", "lrt", "tj")

# Matches each mode's CUTOFF_M in output/isochrone_*.py - the network was only fetched/
# kept out to this distance from each station, so a request for a bigger radius isn't
# safely coverable from that mode's file. TJ is 400m (halte are far denser than MRT/
# KRL/LRT stations, see isochrone_tj.py), the rest are 800m.
MODE_RADIUS_M = {"mrt": 800, "krl": 800, "lrt": 800, "tj": 400}

_roads: dict[str, list[dict]] = {}
_trees: dict[str, STRtree] = {}
_lines_m: dict[str, list] = {}
_roads_loaded: set[str] = set()


def _load(mode: str):
    """One mode's road file only - the old version loaded all 4 modes' roads (TJ alone is
    ~29MB of geojson) the instant any lookup ran, so the first static-mode request of a
    process session paid for parsing every mode's network before answering a query about
    just one of them. Per-mode loading spreads that cost across whichever modes actually
    get queried; each mode is still only ever read once (cached in _roads_loaded)."""
    if mode in _roads_loaded:
        return
    path = STATIC_DIR / f"isochrone_{mode}_roads_{MODE_RADIUS_M[mode]}m.geojson"
    roads: list[dict] = []
    lines_m: list = []
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        for f in data["features"]:
            coords = f["geometry"]["coordinates"]
            props = f["properties"]
            roads.append({
                "coords": coords,
                "highway": props.get("highway", ""),
                "sidewalk": props.get("sidewalk", ""),
                "lit": props.get("lit", ""),
                "surface": props.get("surface", ""),
                "wheelchair": props.get("wheelchair", ""),
            })
            lines_m.append(LineString([to_m(Point(lon, lat)) for lon, lat in coords]))
    _roads[mode] = roads
    _lines_m[mode] = lines_m
    _trees[mode] = STRtree(lines_m) if lines_m else STRtree([])
    _roads_loaded.add(mode)


def has_mode(mode_label: str) -> bool:
    mode = (mode_label or "").lower()
    if mode not in _MODES:
        return False
    _load(mode)
    return bool(_roads.get(mode))


def roads_near(mode_label: str, lon: float, lat: float, radius: int) -> list[dict] | None:
    """Roads from the precomputed static network within `radius` of (lon, lat), or None
    if this mode has no static data yet or `radius` exceeds that mode's MODE_RADIUS_M -
    the caller should fall back to a live osm.roads() call in either case."""
    mode = (mode_label or "").lower()
    if mode not in _MODES or radius > MODE_RADIUS_M.get(mode, 0):
        return None
    _load(mode)
    roads = _roads.get(mode)
    if not roads:
        return None
    origin_m = to_m(Point(lon, lat))
    circle = origin_m.buffer(radius)
    tree = _trees[mode]
    lines = _lines_m[mode]
    idxs = tree.query(circle)
    return [roads[i] for i in idxs if lines[i].intersects(circle)]


_route_geoms_m: dict[str, list] = {}
_route_trees: dict[str, STRtree] = {}
_routes_loaded = False


def _load_routes():
    global _routes_loaded
    if _routes_loaded:
        return
    for mode in _MODES:
        path = STATIC_DIR / f"isochrone_{mode}_routes.geojson"
        geoms: list = []
        if path.exists():
            data = json.loads(path.read_text(encoding="utf-8"))
            geoms = [to_m(shape(f["geometry"])) for f in data["features"]]
        _route_geoms_m[mode] = geoms
        _route_trees[mode] = STRtree(geoms) if geoms else STRtree([])
    _routes_loaded = True


def routes_near(lon: float, lat: float, radius: int) -> int | None:
    """Count of transit route relations (any mode with static coverage) passing within
    `radius` of (lon, lat) - mirrors osm.routes()'s old live Overpass count, but reads
    output/isochrone_*.py's precomputed routes.geojson instead. None if no mode has any
    static route file yet, so the caller can fall back to a live osm.routes() call."""
    _load_routes()
    if not any(_route_geoms_m.values()):
        return None
    origin_m = to_m(Point(lon, lat))
    circle = origin_m.buffer(radius)
    count = 0
    for mode in _MODES:
        geoms = _route_geoms_m[mode]
        idxs = _route_trees[mode].query(circle)
        count += sum(1 for i in idxs if geoms[i].intersects(circle))
    return count


_iso_by_mode: dict[str, dict[str, object]] = {}
_iso_loaded: set[str] = set()


def _load_isochrones(mode: str):
    """One mode's isochrone file only - isochrone_for() only ever needs the requesting
    station's own mode, but TJ's file alone is ~60MB (thousands of halte polygons), so
    loading all 4 modes on the first isochrone lookup of any mode used to tax every
    session with that regardless of which mode was actually asked for."""
    if mode in _iso_loaded:
        return
    path = STATIC_DIR / f"isochrone_{mode}_isochrone_{MODE_RADIUS_M[mode]}m.geojson"
    key_field = "stop_id" if mode == "tj" else "id"
    lookup = {}
    if path.exists():
        data = json.loads(path.read_text(encoding="utf-8"))
        for f in data["features"]:
            sid = f["properties"].get(key_field)
            if sid:
                lookup[sid] = shape(f["geometry"])
    _iso_by_mode[mode] = lookup
    _iso_loaded.add(mode)


_stations: list[dict] | None = None


def stations() -> list[dict] | None:
    """MRT/KRL/LRT station list from output/isochrone_*.py's precomputed
    isochrone_{mode}_stations.geojson (already has id/name/mode_label/operator - those
    scripts enumerate stations as their first step anyway). TJ is never in here - it's
    served straight from GTFS instead (see gtfs.py / main.py's _tj_stations()), which is
    itself a local file, not a live call. None if none of the 3 files exist yet, so the
    caller falls back to a live osm.stations() Overpass call."""
    global _stations
    if _stations is None:
        out = []
        for mode in ("mrt", "krl", "lrt"):
            path = STATIC_DIR / f"isochrone_{mode}_stations.geojson"
            if not path.exists():
                continue
            data = json.loads(path.read_text(encoding="utf-8"))
            for f in data["features"]:
                lon, lat = f["geometry"]["coordinates"]
                out.append({**f["properties"], "lon": lon, "lat": lat})
        _stations = out
    return _stations or None


def isochrone_for(mode_label: str, station_id: str, radius: int):
    """The precomputed entrance-aware isochrone polygon (metric, EPSG:32748) for this
    exact station, or None if not covered. Only ever a hit when `radius` equals that
    mode's MODE_RADIUS_M - the one cutoff isochrone_*.py actually computed, walking from
    every real OSM entrance/exit it found for the station (see output/isochrone_*.py's
    station_isochrone) instead of a single center point. There's no accessible-routing
    (wheelchair-aware) variant of this precomputed shape - callers still need to compute
    that one live from the road graph."""
    mode = (mode_label or "").lower()
    if mode not in _MODES or radius != MODE_RADIUS_M.get(mode):
        return None
    _load_isochrones(mode)
    poly = _iso_by_mode.get(mode, {}).get(station_id)
    return to_m(poly) if poly is not None else None
